version: '2.0'

dir_rule:
  base_dir: /dir/to/your/path  #下载的全部图片文件的路径
  rule: Bd_Aid_Pindex

client:
  impl: html
  domain:
    html:
     - 18comic.vip
     - 18comic.ink
     - jmcomic-zzz.one
     - jmcomic-zzz.org
     - jm18c-tcb.net
    api:
      - jmcomic-zzz.one


download:
  cache: true # 如果要下载的文件在磁盘上已存在，不用再下一遍了吧？
  image:
    decode: true # JM的原图是混淆过的，要不要还原？
    suffix: .jpg # 把图片都转为.jpg格式
  threading:
    # batch_count: 章节的批量下载图片线程数
    # 数值大，下得快，配置要求高，对禁漫压力大
    # 数值小，下得慢，配置要求低，对禁漫压力小
    # PS: 禁漫网页一般是一次请求50张图
    batch_count: 10
plugins:
  after_init:
    - plugin: login # 登录插件，适用于下载某些需要登录可见的本子
      kwargs:
        username:  username # 用户名
        password:  password # 密码
    - plugin: auto_set_browser_cookies # 自动获取浏览器cookies，详见插件类代码→AutoSetBrowserCookiesPlugin
      kwargs:
        browser: firefox
        domain: 18comic.vip
  after_album:
    - plugin: img2pdf
      kwargs:
        pdf_dir: /pdf/to/your/path # pdf存放文件夹,推荐放在base_dir路径下
        filename_rule: Aid # Aname # pdf命名规则，A代表album, name代表使用album.name也就是本子名称
