version: '2.0'

dir_rule:
  base_dir: /dir/to/your/path  #下载的全部图片文件的路径，如果是Windows参考Windows系统的路径撰写格式
  rule: Bd_Aid_Pindex

client:
  impl: api #如需走代理，请将api修改为html
  domain:
    html:
     - 18comic.vip
     - 18comic.ink
     - jmcomic-zzz.one
     - jmcomic-zzz.org
     - jm18c-tcb.net
    api:
      - www.cdnhth.club
      - www.cdngwc.cc
      - www.cdngwc.net
      - www.cdngwc.club
      - www.cdnhjk.cc


download:
  cache: true # 如果要下载的文件在磁盘上已存在，不用再下一遍了吧？
  image:
    decode: true # JM的原图是混淆过的，要不要还原？
    suffix: .jpg # 把图片都转为.jpg格式
  threading:
    # batch_count: 章节的批量下载图片线程数
    # 数值大，下得快，配置要求高，对禁漫压力大
    # 数值小，下得慢，配置要求低，对禁漫压力小
    # PS: 禁漫网页一般是一次请求50张图
    batch_count: 10
plugins:
  after_init:
    # - plugin: login # 登录插件，凡是走这个插件登录的都必定会是403了
    #   kwargs:
    #     username:  username # 用户名
    #     password:  password # 密码
    # - plugin: auto_set_browser_cookies # 自动获取浏览器cookies，我用firefox反正没成功过
    #   kwargs:
    #     browser: chrome
    #     domain: 18comic.vip
  after_album:
    - plugin: img2pdf
      kwargs:
        pdf_dir: /pdf/to/your/path # pdf存放文件夹,推荐放在base_dir路径下，如果是Windows同上
        filename_rule: Aid # Aname # pdf命名规则，A代表album, name代表使用album.name也就是本子名称
